"""empty message

Revision ID: 556a296d625d
Revises: b93865394263
Create Date: 2022-06-04 18:41:39.177100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556a296d625d'
down_revision = 'b93865394263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('image_link', sa.String(length=500), nullable=False))
    op.add_column('artist', sa.Column('facebook_link', sa.String(length=120), nullable=False))
    op.add_column('artist', sa.Column('genres', sa.String(length=100), nullable=True))
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=500), nullable=False))
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('artist', sa.Column('website_link', sa.String(length=120), nullable=False))
    op.add_column('artist', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'artist', 'city', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'city_id')
    op.drop_column('artist', 'website_link')
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'seeking_description')
    op.drop_column('artist', 'genres')
    op.drop_column('artist', 'facebook_link')
    op.drop_column('artist', 'image_link')
    # ### end Alembic commands ###
