"""empty message

Revision ID: 55da1a6810d2
Revises: 5387f22a44da
Create Date: 2022-06-04 05:14:14.830388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55da1a6810d2'
down_revision = '5387f22a44da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('artist', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'artist', 'city', ['city_id'], ['id'])
    op.drop_column('artist', 'city')
    op.drop_column('artist', 'state')
    op.add_column('venue', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venue', 'city', ['city_id'], ['id'])
    op.drop_column('venue', 'city')
    op.drop_column('venue', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_column('venue', 'city_id')
    op.add_column('artist', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'city_id')
    op.drop_table('city')
    # ### end Alembic commands ###
