"""empty message

Revision ID: 834013c29532
Revises: 556a296d625d
Create Date: 2022-06-04 19:54:39.505349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834013c29532'
down_revision = '556a296d625d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
