"""empty message

Revision ID: a77e249e48ee
Revises: 834013c29532
Create Date: 2022-06-08 00:31:52.062569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77e249e48ee'
down_revision = '834013c29532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('venue', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'created_date')
    op.drop_column('artist', 'created_date')
    # ### end Alembic commands ###
